### ISSUE TITLE
Typo3 v9

### ISSUE THREAD

**Issue by ipnextOne** [bihor/fp_newsletter#1]
Hello,

is Typo3 v9 support planned?

Thanks 
Mathias

**Comment by bihor** [comment]
Yes, TYPO3 9 support is planned, but I haven´t used TYPO3 9 yet.
I guess, I will do that in the next weeks.

**Comment by ipnextOne** [comment]
Very nice. 

Thanks a lot

**Comment by bihor** [comment]
There is no direct_mail version for TYPO3 9.5.
Do you need the extension for something else?

**Comment by ipnextOne** [comment]
I need it for direct_mail, but at the moment i will only collect email addresses untel direct_mail for 9.5 is come

**Comment by bihor** [comment]
OK, the extension should now run with TYPO3 9 too when typo3db_legacy is installed.

**Comment by zolthan** [comment]
Are there plans to natively support Typo3 v9, without typo3db_legacy?

**Comment by bihor** [comment]
Yes, I guess I will natively support TYPO3 v9 in future versions.

**Comment by bihor** [comment]
OK, it works now with the Doctrine / QueryBuilder.
