### ISSUE TITLE
Direct mail categories not availiable

### ISSUE THREAD

**Issue by xmental** [bihor/fp_newsletter#10]
Although defined in setup.typoscript with module_sys_dmail_category = 1,2,3 categories are not generated.
Setup: TYPO3 9.5 LTS, Direct Mail BUGFIX: https://github.com/vzz3/direct_mail
and of course fp_newsletter 0.16.0

Missing feature or bug?

**Comment by bihor** [comment]
First: I see this at that direct_mail version:
'typo3' => '7.6.0-8.99.99',

Second: this extension does the same like direct_mail_subscription. I have added a explanation here:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/master/en-us/Configuration/Index.html

Question: which result do you expect?

**Comment by xmental** [comment]
First: Hot quickfix but it works
Second: Just display direct mail categories to select in the subscription form

**Comment by bihor** [comment]
Well, then I need to store the categories in the log-tables too.
Maybe in the next versions.

**Comment by xmental** [comment]
Would be very useful :-)

**Comment by bihor** [comment]
Is a text-field OK?
Or do you prefer DB-relations?
I have added a textfield...

**Comment by xmental** [comment]
sorry for may very delayed reply. You meant, selected direct mail categories are stored in a text field. Imho for a start it will work and of course db relations are better.

**Comment by bihor** [comment]
Well, the categories will be added now via hidden-field to the log-entry as text-field. (version 0.17.6)
You could add checkboxes and copy the checked values by jQuery to the hidden-field if you need a more flexible solution.
For you it should not matter where the categories are stored in the database.
