### ISSUE TITLE
Feature Request: Set address to hidden instead of deleting

### ISSUE THREAD

**Issue by riegeo** [bihor/fp_newsletter#100]
Hi,
is there a possibility to just hide the tt_address entry if someone unsubscribes from the newsletter?

I tried this setting but the address is deleted anyway.

`plugin.tx_fpnewsletter.settings.deleteMode = 1`

Thank you

**Comment by bihor** [comment]
Well, currently it is not possible:
1: set deletion flag; 2: delete entry; 3: remove only the cat./group
I could add 4: hide entry.

**Comment by bihor** [comment]
OK, I have added this in version 7.0.5.
You can use it now.

**Comment by riegeo** [comment]
Thank you very much

**Comment by agendartobias** [comment]
Hey, are you sure that this is working? We have tried it on TYPO3 v13 and latest v9 extension and everytime only category/group is deleted. i have set via typoscript + via flexform hard delete of user

**Comment by bihor** [comment]
Well, I have just tested it with fe_users and tt_address.
With mode 4 the user was set to hidden.
Which delete mode did you used?

**Comment by agendartobias** [comment]
Oh i see that's the problem. I used "LUXletter: Quick unsubscribe" plugin instead of fp_newsletter plugin called: "Newsletter: unsubscribe via Luxlettter-link". Nov everything is OK!

Thank you!
