### ISSUE TITLE
'missing direct_mail' after Update to 7.0

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_newsletter#102]
After updating to 7.0 There id a red info box above my form: 'missing direct_mail'

**Comment by linawolf** [comment]
I am not using direct mail nor have I before the update

**Comment by linawolf** [comment]
Ok so I had copied the template to make changes and it still had the old error message in it.

**Comment by bihor** [comment]
Completed?
I guess you hadn´t set settings.table.
