### ISSUE TITLE
Unsubscribe per Formular not working

### ISSUE THREAD

**Issue by soerenwachsmuth** [bihor/fp_newsletter#104]
Hi there,

I'm using fp_newsletter v7.0.5 on a TYPO3 12.4.20 with the standard templates brought within the extension.
I (think) I set up everything correct within flexform and TypoScript.
I added all pages in the flexform and added the settings.unsubscribeUid also in TS. (as I read that might be a problem)
I'm using fe_users as table for the registration and the subscription is working.

When I try to submit the ubsubscribe form nothing happens. When I open up the action link in the form it shows the error from the error message  uid 1.
I debugged through the controller and found the error that was thrown:
It's in the LogController line 921. So the $log is empty there is no email set it seems.

Am I missing something? 

Thank you for any help!
Best regards,
Sören

**Comment by bihor** [comment]
Yes, this is a know problem: there are more plugins and it depends from where you submit to where.
So I need to know what you have selected on page 1 and which plugin you have selected on page 2.
On page 1 its sometimes necessary to set the plugin-key for page 2 with:
pluginName="xxx"
in the form.
So I guess in this case the pluginName is wrong.
I didn´t find an automatic solution till now...

**Comment by soerenwachsmuth** [comment]
Thank you for the answer.

So I set up the pages the same in the FlexForm in both plugins. 
![grafik](https://github.com/user-attachments/assets/b27fd1da-d819-416f-a977-76b0165dadc4)

So on the unsubscribe page 218 is the plugin unsibscribe and on the 481 is the unsubscribe verify.

I tried to set in the f:form in the unsubscribe.html template the unsibscribeVerifyUid and setting the pluginName to verifyUnsubscribe
<f:form pageUid="{unsubscribeVerifyUid}" pluginName="verifyUnsubscribe" action="delete" name="log" object="{log}">

But it didnt change a thing.

**Comment by bihor** [comment]
I am still not sure, from where you submit the form.
From the a page with a subscription + unsubscription form?
Or from the page 218.
If you submit the form from page 218 it should work without any problems.
Page 218 should use the Unsubscribe.html template and the form should looks like this image:
![unsubscribe](https://github.com/user-attachments/assets/61e9d514-adab-4469-84f9-e38eeb4d45c3)

PS: its normal that the link without post-parameters does not work:
https://typo3-12.test/testseiten/abmelden?tx_fpnewsletter_unsubscribe%5Baction%5D=delete&tx_fpnewsletter_unsubscribe%5Bcontroller%5D=Log&cHash=95ef6c28aeda4ffa4d81e2588ac14f4f

**Comment by soerenwachsmuth** [comment]
Yes, I'm submitting from the page 218 and the form itself is looking good I think:
![grafik](https://github.com/user-attachments/assets/2f01bfc7-ddef-413d-ade1-3721e63ecf30)

I'm using the standard templates from the extension in this example.
