### ISSUE TITLE
Alternative to Google reCaptcha

### ISSUE THREAD

**Issue by chris246** [bihor/fp_newsletter#11]
Hi,

would it be possible to support a more privacy-friendly alternative to Google's reCaptcha, e.g. solving a math question (8-3) and validating it server-side without the need of a third party?

**Comment by bihor** [comment]
I will try it.

**Comment by chris246** [comment]
Hi, 

thank you very much, that looks great.
In a first test (I did not use the extension before), everything worked fine.

Some suggestions:
Change "Math. Captcha" label to something like "Spam protection" or directly give the task "Enter the result of y - z here" (give the numbers directly), then the sentence behind the input would also not be necessary. 
I think, that the formula x = y-z might awake bad memories to math lessons from long ago ;-)

Also (although not very urgent) you could also let users solve sums and chose the operation randomly. So one user calculates x-y, and another a+b

**Comment by bihor** [comment]
OK, I have mad some changes.
