### ISSUE TITLE
The domain is missing in the emails when using TYPO3 9

### ISSUE THREAD

**Issue by Balindil** [bihor/fp_newsletter#13]
Hi,

I use TYPO3 v9. In the verification email there is the correct domain missing. Link that shown:
`/?no_cache=1&tx_fpnewsletter_pi1%5Baction%5D=verify&tx_fpnewsletter_pi1%5Bcontroller%5D=Log&tx_fpnewsletter_pi1%5Bhash%5D=f40489d50a36262359c0ab77332ff464&tx_fpnewsletter_pi1%5Buid%5D=2&cHash=b6b51966bd0342d69042d1eab7924c57`

**Comment by bihor** [comment]
Yes, I noticed that too, but I think it is because you have entered / at the Entry Point field in the Site configuration.
You need to enter there https://www.your-domain.com/
I guess, the domain is coming from there.

**Comment by Balindil** [comment]
You are right! After changing entry point there is the right link in the verification email.
Thanks and regards.
