### ISSUE TITLE
Use plugin more then once on a page

### ISSUE THREAD

**Issue by Balindil** [bihor/fp_newsletter#14]
Hi,

is there a possibility to use this plugin more than once on a page? Perhaps one time in content and once more in the footer. I tried this and for every plugin on a page there is one verification email sent.

**Comment by bihor** [comment]
That is a general problem of TYPO3 extensions.
Therefore there is the feature to accept parameters from other Forms / other extensions:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/master/en-us/Configuration/Index.html#property-details
You can add an normal HTML-form to your footer and read the parameter from that form via this feature.

**Comment by Balindil** [comment]
Thank you, i will try this.
