### ISSUE TITLE
Not working in other languages than the default one

### ISSUE THREAD

**Issue by tilman82** [bihor/fp_newsletter#15]
Hi,

Got a multilanguage setup here, the verifyAction throws an error in all other languages than the default one with UID=0.

Guess that's the reason:

- All log entries are created with sys_language_uid=0.
- The generic repository function findOneByUid() respects the actual language and can't find the records for other languages.

I found commented code in the createAction and the log model regarding the sys_language_uid, with this code it works...

For me it also would be fine to set all the records to sys_language_uid=-1, as those user generated records will never be translated and I only know scenarios where multilingual newsletters are solved with the direct mail categories.

**Comment by bihor** [comment]
Yes, you are right - it does not work.
I need to find a solution...

**Comment by bihor** [comment]
Is in the current version implemented. Have you tested it already?

**Comment by tilman82** [comment]
Works like a charm, thanks a lot!!!
