### ISSUE TITLE
Add more fields from tt_address to the optional fields

### ISSUE THREAD

**Issue by tilman82** [bihor/fp_newsletter#16]
Hi,

For a registration for a press release newsletter I need more fields from tt_address in the signup form and the admin email:
- www
- company
- phone
- address
- zip
- city
- country
- (any more?)

Could you please add them to the optionalFields setting?

Any ideas how we could create a sorting option for the optional fields, or maybe respect the ordering in the optionalFields itself?

**Comment by tilman82** [comment]
Ok, sorting can be done manually in the fluid template, so forget the last question ;-)

**Comment by bihor** [comment]
OK, done in Version 0.17.5
