### ISSUE TITLE
not able to change Inner Email text  and send email verification link in email

### ISSUE THREAD

**Issue by krunal16071985** [bihor/fp_newsletter#17]
Please suggest me how can I change Email text and send Email verification link in Email
https://prnt.sc/q2msxq

**Comment by bihor** [comment]
Well, you need to copy the Email-Templates to fileadmin and than you can change the text.
The files are here:
Resources/Private/Templates/Email/
Than you need to change the path to the templates like this:
plugin.tx_fpnewsletter.view.templateRootPaths.1 = fileadmin/bsdist/theme/tmpl/fp_newsletter/Templates/

**Comment by krunal16071985** [comment]
Thanks for information.
Please tell me how to place Email verification Link in Email. This is my template which send to user for subscribe but email link are not include in this.
typo3conf/ext/t3oea/Resources/Private/ext/fp_newsletter/Templates/Email/SubscribeVerify.html

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Newsletter</title>
</head>
<body>
<h3>Guten Tag,</h3>
<p>um sich zu unserem Newsletter anzumelden, müssen Sie Ihre E-Mailadresse mit Klick auf diesen Link verifizieren:</p>
<p><f:link.action pageUid="{subscribeVerifyUid}" extensionName="fpnewsletter" pluginName="pi1" controller="Log" action="verify" arguments="{uid: uid, hash: hash}" noCache="1" absolute="1"><f:uri.action pageUid="{subscribeVerifyUid}" extensionName="fpnewsletter" pluginName="pi1" controller="Log" action="verify" arguments="{uid: uid, hash: hash}" noCache="1" absolute="1" /></f:link.action></p>
<p>Mit freundlichen Grüßen<br>
{settings.company}</p>
</body>
</html>

**Comment by bihor** [comment]
This is how the link is build:
<f:format.raw><f:uri.action pageUid="{subscribeVerifyUid}" extensionName="fpnewsletter" pluginName="pi1" controller="Log" action="verify" arguments="{uid: uid, hash: hash}" noCache="1" absolute="1" /></f:format.raw>

It should work if you specify the subscribeVerifyUid vis TypoScript:
plugin.tx_fpnewsletter.settings.subscribeVerifyUid = 24
