### ISSUE TITLE
Domain is set, but no Domain is in E-Mail

### ISSUE THREAD

**Issue by quadronet** [bihor/fp_newsletter#18]
Hello i have setup the domain in the TYPO3 9.7,11,  but the domain is not in the email. 

I solved this by delete the f:link action and wrote the domain in the template:

<f:format.raw>https://www.domain.de<f:uri.action pageUid="{subscribeVerifyUid}" extensionName="fpnewsletter" pluginName="pi1" controller="Log" action="verify" arguments="{uid: uid, hash: hash}" noCache="1" absolute="1" /></f:format.raw>

but, what´s wrong in the extension?

**Comment by bihor** [comment]
I don´t know. The link is generated by TYPO3 and not by the extension.
