### ISSUE TITLE
new captcha don´t work.

### ISSUE THREAD

**Issue by quadronet** [bihor/fp_newsletter#19]
Nice feature, but it don´t work, after send the form this error is shown:

(1/2) #1297759968 TYPO3\CMS\Extbase\Property\Exception
Exception while property mapping at property path "": Property "mathcaptcha" was not found in target object of type "Fixpunkt\FpNewsletter\Domain\Model\Log".

in /var/www/vhosts//typo3_src-9.5.9/typo3/sysext/extbase/Classes/Property/PropertyMapper.php line 120

**Comment by bihor** [comment]
Well, I don´t know how you have updated the extension.
If you have updated it from the Git, then you need to reinstall the extension again.
That should solve the problem.
