### ISSUE TITLE
Subscription mail send 2x

### ISSUE THREAD

**Issue by szagunn-binaco** [bihor/fp_newsletter#2]
Installed the extension, configured it, plugin is sending the subscription mail 2x.

**Comment by bihor** [comment]
Do you use the plugin twice on one site?
Because there is only one call of $this->sendTemplateEmail.

**Comment by szagunn-binaco** [comment]
Hi,

only in Translations. (DE/EN/NL)

Best regards
Dirk

Am 18.02.19 um 10:01 schrieb Kurt Gusbeth:

**Comment by bihor** [comment]
Well, there is no sys_language_uid field in tt_address. Maybe that is a problem, but I don´t think so.
I have tested the extension I didn´t found any error till now.
I have added double opt out now too.
Can you test if that email is send twice too?
