### ISSUE TITLE
Problems with the docs

### ISSUE THREAD

**Issue by fischhase** [bihor/fp_newsletter#22]
Dear Kurt,

I configured your subscription ext and it works in terms of subsciption. Thank you for your work. It is really easy. 
But ... Unfortunately I could not find out how to place an unsubscription form. I fill all setting parameters and its UIDs. When opening the unsubscription page with the plugin, the subscriptionform appears. 

There is an option to show the unsubscription form under the subscription form. If I use this option (what in deed is an option), I get an exception with the error "The action "delete" (controller "Log") is not allowed by this plugin. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php."

You also tell, that a different unsubscripe UID is obligatory; so I really don't know, how to place the plugins. An example in the documentation would be great.

Thank you 
Martin

**Comment by bihor** [comment]
You can configure a page for the unsubscription via FlexForm or TypoScript.
On the Unsubscription page select "unsubscribe via form" in the plugin.
That should work.
![unsub](https://user-images.githubusercontent.com/8191408/74758301-71ad7380-5277-11ea-9e3c-4066f5b1cf44.jpg)
