### ISSUE TITLE
HoneyPot

### ISSUE THREAD

**Issue by seirerman** [bihor/fp_newsletter#23]
We can't use reCaptcha due to client (local government) policy of not using 3rd party plugins.

mathCaptcha works, but have you thought about adding a honeypot field to prevent spam?
A lot of users don't like captchas, and this would also help with accessibility.

Great extension, btw! A modern and worthy successor to direct_mail_subscription!

**Comment by bihor** [comment]
Yes, Honeypot is a good idea.

**Comment by bihor** [comment]
A honeypot will be a input form element with no content that is not visible:
https://www.clickstorm.de/blog/alternativen-captchas-honeypot-blacklist/
Is that the idea you have?
Or have you another idea about a honeypot?

**Comment by bihor** [comment]
Implemented in version 1.0.6.
