### ISSUE TITLE
Emails are no send to user with mailjet

### ISSUE THREAD

**Issue by yohannPiment** [bihor/fp_newsletter#26]
Hello,

I've a problem with the extension, I've configured my mailjet account to send email with typo3 but when user subscribe to the website, no email are send. It's not my mailjet configuration because it works with powermail extension. 
Do you have an idea about this ?

Thx
Yohann

**Comment by bihor** [comment]
Well, I am using the mailer from TYPO3:
TYPO3\\CMS\\Core\\Mail\\MailMessage
It shoould work if
settings.email.senderMail and settings.email.senderName are set.
If you have no idea, you must debug the method sendTemplateEmail in the file Classes/Controller/LogController.php

**Comment by bihor** [comment]
If you have configured the smtp-server in the TYPO3 configuration, it should send any email from TYPO3:
https://www.mailjet.com/de/produkte/email-api/smtp-relay/
