### ISSUE TITLE
Add "resend confirmation link"

### ISSUE THREAD

**Issue by rowild** [bihor/fp_newsletter#28]
Since you have a To-Do list, I would like to propose to add above mentioned feature.

I keep this here as a reminder, maybe I can provide a PR.

**Comment by bihor** [comment]
Where would you like to have the "resend confirmation link"?

**Comment by rowild** [comment]
I'd rather think of a plugin that consists of an input field for the email address and the resend Confirmation button. The integrator can then place it anywhere.

**Comment by bihor** [comment]
Do you mean: resend a verification email?
Then you could refill the whole form. That works.
There was no confirmation email till version 1.2.4.
For me a confirmation email is an email that says: you have successfully subscribed to the newsletter.

**Comment by rowild** [comment]
@bihor Sorry for my absence! Yes, you are right, of course: it should be a "resend verification email" feature

**Comment by bihor** [comment]
OK, I have added this feature in version 2.4.0.
You can define the new page via settings.resendVerificationUid
