### ISSUE TITLE
module_sys_dmail_html = 1 does not work

### ISSUE THREAD

**Issue by rowild** [bihor/fp_newsletter#29]
Setting the above mentioned option does not work as I would expect – which is: once it is configured to be "1", all users will automatically be set to receive text AND html mails. (At least this is what the docu makes me believe...)

What do I have to do to automatically activate the HTML checkbox, so that users receive text and html?

**Comment by bihor** [comment]
The field module_sys_dmail_html is been setting to tt_address during the insert-procedure.
This happens after the verification.
For me it works.

**Comment by rowild** [comment]
When I look at an existing tt_address record that was confirmed, the "Receive emails as HTML" checkbox is not checked. 

Also, when the log is created, there does not seem to be a field that holds that value (screenshot 2).

The TypoScript is, I would assume, set correctly:

```
plugin.tx_fpnewsletter {
  settings {
	table = tt_address
	// optionalFields = gender,firstname,lastname
	optionalFields =
	optionalFieldsRequired =
	gdprUid = 20
	daysExpire = 2
	deleteMode = 2
	module_sys_dmail_html = 1
	module_sys_dmail_category =
       [...]

  }
}
```

TYPO3 9.5
fp_newsletter 1.1.0

Do I misunderstand something here? Or do I configure the plugin wrongly?

Thank you!

![Screen Shot 2020-08-05 at 07 59 01](https://user-images.githubusercontent.com/213803/89377337-de1b1280-d6f1-11ea-9af5-c3e033218c4e.png)
![Screen Shot 2020-08-05 at 07 59 43](https://user-images.githubusercontent.com/213803/89377708-ab254e80-d6f2-11ea-9dcd-c5f35fe3ee29.png)

**Comment by rowild** [comment]
And when I enter this

```
    public function verifyAction()
    {
    	$error = 0;
    	$dbuid = 0;
    	$email = '';
	$html = intval($this->settings['module_sys_dmail_html']);

	echo("<pre>");
	var_dump( $html);
	echo("</pre>");
	die();
```

in LogController, I get "int(-1)"

**Comment by bihor** [comment]
-1 means: ignore the field.
Have you checked in the FlexForm-settings of the plugin "ignoriere dieses Feld"?

**Comment by rowild** [comment]
Indeed, the verification page had it set to "ignore". Thank you!
