### ISSUE TITLE
"Unsubscribe via link" does not work

### ISSUE THREAD

**Issue by rowild** [bihor/fp_newsletter#30]
I am not sure, in how far this is related to direct_mail or this extension - please forgive me, if I am in the wrong place!

I out this unsubscribe link in my Fluid template of the DirectMail Newsletter:

```
<p>Vom Newsletter <b><a style="font-size: 12px;" href="http://newsletter.domain.tld/abmeldung-via-link/?u=###USER_uid###&t=###SYS_TABLE_NAME###&a=###SYS_AUTHCODE###" title="abmelden">abmelden</a></b></p>
```

When I send to newsletter to myself (DirectMail step 4), the link in the newsletter reads like this:

```
http://newsletter.domain.tld/newsletter-2?mid=11&aC=85b5531&jumpurl=3
```

But when I click on it, the URL in the Browser read like this:

```
https://newsletter.domain.tld/abmeldung-via-link/?u=###USER_uid###&t=###SYS_TABLE_NAME###&a=###SYS_AUTHCODE###
```

The page is actually correct, and the plugin there is "unsubscribe via link". The page outputs the error message `Fehler - Der Abmelde-Link konnte nicht verarbeitet werden.`

It seems as if direct_mail does not replace the markers. Or is it fp_newsletter?

Any idea where the culprit of my setup could be?

**Comment by bihor** [comment]
Well, the unsubscribe link works only for users in tt_address.
At step 4 you give directly an email address.
Thats why it does not work in this case.
You need to send a newsletter to a group to test this feature.

**Comment by rowild** [comment]
I am still confused, because 
1. those emails in step 4 are defined via ids from tt_address;
2. the newsletter's unsubscribe link is generated correctly.

But since it also does not work with a regular list of recipients, my setup is somewhere somehow messed up. I ended up using the unsubscribe input field with the optout option. That way I only need to send the link to the unsubscribe page. and that works perfectly fine.

Thank you very much for your quick responses! Very much appreciated!
