### ISSUE TITLE
Unable to send Unsubscription Verification Mail 

### ISSUE THREAD

**Issue by notacoder-ui** [bihor/fp_newsletter#31]
Hi @bihor 

I have set up the extension in typo3 9.5.19.

I get mail when using the subscription form to subscribe and can get the verification mail also with the link to get verified.
But, when I try to unsubscribe using the form I do not receive any mail that is unsubscribed.
Do I need to enable anything in the setup.ts?

could you please help me with this?

**Comment by bihor** [comment]
There is no email that says you, that you are unsubscribed now.
This message is displayed only after unsubscription.
This would be a feature for next versions.

**Comment by notacoder-ui** [comment]
Okay, Thanks

**Comment by bihor** [comment]
You can enable doubleOptOut to recieve an email un unsubscription via
settings.doubleOptOut=1
And since version 1.2.4 you can enable confirmations emails too via
settings.email.enableConfirmationMails=1
