### ISSUE TITLE
unsubscribe for various folders

### ISSUE THREAD

**Issue by pbuenemann** [bihor/fp_newsletter#34]
Hi,
subscribers cannot unsubscribe if they are organized in different folders. I can only specify one storagePid. A specification like plugin.tx_fpnewsletter.persistence.storagePid = 6,7,8 does not work.

**Comment by bihor** [comment]
OK, you can try this with the setting searchPidMode=1
in version 2.0.4

**Comment by pbuenemann** [comment]
Hi,
many thanks for this.
Works here, but the mail-address ist not found when
doubleOptOut = 1 is set.

**Comment by bihor** [comment]
OK, it works now for doubleOptOut = 1 too.
