### ISSUE TITLE
[Docu] should "_pi1" example be adapted?

### ISSUE THREAD

**Issue by rowild** [bihor/fp_newsletter#39]
In the changelog you mention that you renamed the plugin:

`Wichtige Änderung: plugin.tx_fpnewsletter_pi1 umbenannt nach plugin.tx_fpnewsletter, weil sonst leere TypoScript-Werte vorhandene FlexForm-Werte überschreiben.`

The docu still present code examples the use "_pi1" under "optionale Felder" and "Benutzung von Kategorien":
https://docs.typo3.org/p/fixpunkt/fp-newsletter/main/de-de/Configuration/Index.html#optionale-und-erforderliche-felder

Shouldn't those be adapted, too?

**Comment by bihor** [comment]
You are right.
I have changed it in version 2.2.2.
