### ISSUE TITLE
fp_newsletter without direct_mail

### ISSUE THREAD

**Issue by chrcan** [bihor/fp_newsletter#41]
is it possible to run fp_newsletter without direct_mail…. "Sure it works BUT"
The problem I have if I don't install direct_mail is the checkbox in tt_address “Receive emails in HTML format?” not set.
Since direct_mail for TYPO 11 does not yet exist, it is tedious to edit all addresses afterwards.
Is there a solution for that?

**Comment by bihor** [comment]
Nun, das Feld module_sys_dmail_html kommt aus direct_mail in die tt_address-Tabelle, aber wenn das Feld da ist, 
sollte man es ohne Probleme benutzen können, egal ob direct_mail installiert ist oder nicht.
Hab ich eben getestet. Funktioniert.
Wo genau ist also das Problem?

**Comment by chrcan** [comment]
Sorry kann dir nicht folgen, wenn ich fp_newsletter installiere ist doch das Feld module_sys_dmail_html ja nicht in der DB.
Ist das direct_mail installiert dann ist das ja kein Problem dann sehe ich das auch.
Legst du das per Hand an? 
Also ich sehe da nur diese Felder bei meinen Adressen von tt_address.
Allgemein
Adresse
Kontakt
Sprache
Zugriff
Kategorien
Directmail ---> fehlt weil direc_mail ist nicht installiert

**Comment by bihor** [comment]
Ja, wenn direct_mail noch nie installiert war, fehlt das Feld durchaus.
Deshalb müsste man zuerst direct_mail kurz installieren (und dann wieder deinstallieren).
Eine andere Lösung sehe ich da nicht, denn ich werde das Feld nicht selber hinzufügen.
Zur Not muss man das Feld dann eben in tt_address per Hand hinzufügen.

**Comment by chrcan** [comment]
OK danke!

**Comment by bihor** [comment]
Neuigkeit: wenn direct_mail nicht installiert ist, muss nun ab Version 2.3.0 der Extension-Check in diesem Fall ausgeschaltet werden:
checkForRequiredExtensions = 0

**Comment by chrcan** [comment]
Servus Kurt,

hab die neue Extension ausprobiert und bekomme da immer den gleichen Fehler wenn man auf die Verifizierungsmail klickt, egal was ich einstelle:


Oops, an error occurred!
An exception occurred while executing 'INSERT INTO `tt_address` (`pid`, `tstamp`, `crdate`, `sys_language_uid`, `title`, `first_name`, `last_name`, `name`, `address`, `zip`, `city`, `region`, `country`, `phone`, `mobile`, `fax`, `position`, `company`, `email`, `module_sys_dmail_html`, `gender`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [23, 1647002220, 1647002220, 0, "", "Christian", "Racan", "Christian Racan", "", "", "", "", "", "", "", "", "", "", ***@***.***", 0, "m"]: Unknown column 'module_sys_dmail_html' in 'field list'

module_sys_dmail_html = 0
checkForRequiredExtensions = 0

Was mache ich den da falsch?
Wenn es was hilft bei dem Projekt hab ich das eingebaut direct_mail hab ich deinstalliert :
https://typo.outdoor-experience.at/ <https://typo.outdoor-experience.at/> ganz unten ist der Button Newsletter

Grüße aus Österreich 
Christian Racan

**Comment by bihor** [comment]
Nun, wenn das Feld nicht vorher mit direct_mail angelegt hat, muss man es selber anlegen oder eben ignorieren mit:
module_sys_dmail_html = -1
checkForRequiredExtensions prüft, ob direct_mail installiert ist und ignoriert das Feld ggf. automatisch.
Du willst das Feld wohl befüllen, also gilt weiterhin was unter 
[bihor](https://github.com/bihor) commented [on 20 Dec 2021](https://github.com/bihor/fp_newsletter/issues/41#issuecomment-998062420)
steht.
