### ISSUE TITLE
Unsubscribtion link error #1313855175

### ISSUE THREAD

**Issue by bschmidttraub** [bihor/fp_newsletter#42]
In my installation (Typo3 Vers. 10.4.23) the unsubrscribe action leads to the following error:
#1313855175 TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException
The action "delete" (controller "Fixpunkt\FpNewsletter\Controller\LogController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php.

The generated link seems to be ok. I've double checked if the plugin is in the correct mode (unsubscribe via link). What can I do?
I've found the issue #24 but I've no captcha active.

**Comment by bihor** [comment]
Here you see how to build a unsubscribe link:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/main/en-us/Administrator/Index.html#newsletter
At the target page you need to select "Newsletter: unsubscribe via link".
That should work, because the delete action is allowed for that special page:
Log->unsubscribeDM;Log->delete;Log->verifyUnsubscribe

Maybe you have a page where I can test it?

**Comment by bschmidttraub** [comment]
I've double checked if the plugin is in the right mode. But it doesn't work anyhow...
You can test it via this link: http://update2022.gaertnerei-loewer.de/newsletter-abbestellen-1?u=8655&t=t&a=1181591c
That's the link which comes from the Newsletter
(It's a staging site for a typo3 update and it will only work a few hours...)

**Comment by bihor** [comment]
Well, I have tested your link. The link is OK, but yes, there is an error.
I have tested it with my test-newsletter:
http://server/testseiten/newsletter/sofort-abmeldung?u=21&t=t&a=6456dec3
and it goes to
http://server/testseiten/newsletter/sofort-abmeldung?tx_fpnewsletter_pi1%5Baction%5D=delete&tx_fpnewsletter_pi1%5Buser%5D%5Baddress%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bbirthday%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bbuilding%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcategories%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bcity%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcompany%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcountry%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcrdate%5D=1640012023&tx_fpnewsletter_pi1%5Buser%5D%5Bcruser_id%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bdeleted%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bemail%5D=th%40fixpunkt.com&tx_fpnewsletter_pi1%5Buser%5D%5Bendtime%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bfacebook%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bfax%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bfe_group%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bfirst_name%5D=Kurt&tx_fpnewsletter_pi1%5Buser%5D%5Bgender%5D=m&tx_fpnewsletter_pi1%5Buser%5D%5Bhidden%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bl10n_parent%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Blast_name%5D=Sagan&tx_fpnewsletter_pi1%5Buser%5D%5Blinkedin%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bmobile%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bmodule_sys_dmail_category%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bmodule_sys_dmail_html%5D=1&tx_fpnewsletter_pi1%5Buser%5D%5Bname%5D=Kurt%20Sagan&tx_fpnewsletter_pi1%5Buser%5D%5Bphone%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bpid%5D=29&tx_fpnewsletter_pi1%5Buser%5D%5Bposition%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bregion%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Broom%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bskype%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bsorting%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bstarttime%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bsys_language_uid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_count%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_id%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_label%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_move_id%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_oid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_stage%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_state%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_tstamp%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_wsid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3_origuid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Btitle%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Btstamp%5D=1640012023&tx_fpnewsletter_pi1%5Buser%5D%5Btwitter%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Buid%5D=21&tx_fpnewsletter_pi1%5Buser%5D%5Bwww%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bzip%5D=&cHash=f7fd90c2529c88e15ed780e9db656211
like your link, but I didn´t get any error.
I don´t know, whats wrong in your case...

**Comment by linawolf** [comment]
I am having the same isssue. This happens when you use the following plugin:
![image](https://user-images.githubusercontent.com/48202465/222403158-e1964ca8-a464-44a5-bac2-e92a0a0644c7.png)

And then uppon sending I get the followin error: 
```
The action "delete" (controller "Fixpunkt\FpNewsletter\Controller\LogController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php.
```

**Comment by linawolf** [comment]
Ok, so in my case this happened because I have a fly out for newsletter registration on each and every page:
![image](https://user-images.githubusercontent.com/48202465/222408265-508d86f2-5e1f-4e99-bf7d-9d63b5dca6df.png)

When unregistering the registration form in the flyer is the one who causes this error.

**Comment by bihor** [comment]
Aha. The problem is that there are 2 fp_newsletter plugins in use at the unsubscribe-page.
I think, the only solution is, to remove the second plugin at the unsubscribe page.
An other solution would be, to use a static form on every page. In that case the static form would go to a new-form.
The solution is described here:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/4.1/en-us/Administrator/Index.html#subscription-form-on-every-page

**Comment by bihor** [comment]
I think, this will be no problem with version 5 or 6, because there is now more than one plugin.
