### ISSUE TITLE
Missing Dependency to tt_address

### ISSUE THREAD

**Issue by WorksDev** [bihor/fp_newsletter#43]

**Comment by WorksDev** [comment]
@bihor thanks for your answer - in principle yes, but then at least everything that leads to errors should be initially deactivated - e.g. 1 installation, plugin integrated, request sent, fatal error - because an attempt was made to fill the DirectMail html field.

Apart from that, the same happens with tt_address.

**Comment by bihor** [comment]
You are right, the default mode is to use tt_address and direct_mail and that leads to errors if one of them is not installed.
But I can´t change the default mode.
I think I will implement a setting checkForRequiredExtensions=1

**Comment by bihor** [comment]
OK checkForRequiredExtensions=1 is now implemented in version 2.3.0
