### ISSUE TITLE
Unsubscription Link: Confirmation button

### ISSUE THREAD

**Issue by chris246** [bihor/fp_newsletter#47]
Hi,

as some AntiVirus seems to scan links embedded in emails, it would be great if the "Unsubscribe via Link"-page could get an (optional) button the user needs to click on the complete the procedure.

**Comment by bihor** [comment]
Well, an "Unsubscribe via Link"-page is a page and not an email.
You mean: the verification emails should contain an button???
I have added in version 2.3.2 such a button to the HTML-email templates.
Is that fine?

**Comment by chris246** [comment]
Hi,
I meant the following workflow:

1. User clicks on unsubscribe link in newsletter
2. Unsubscribe via link page opens in browser, displaying a "confirm" button and explanatory text "Click here to unsubscribe" or something like that.
3. User can click on that button or not

This way the unsubscribe can't happen by accident or by software

**Comment by bihor** [comment]
OK, you can enable this feature with dmUnsubscribeMode = 1 in version 2.3.3

**Comment by ambo11** [comment]
It is nice to have this confirmation button in the email template.
Im my case the email-link is working fine, but the button does not have the same URL. The effect is: if you use the button the website opens with "wrong parameters"
Is there a config option to disable the button in emails?

**Comment by bihor** [comment]
You are right. This is a bug!
I have fixed it in version 3.0.0.
The button should now be fine.
