### ISSUE TITLE
Discussion on email handling (locallang and forms).

### ISSUE THREAD

**Issue by lucmuller** [bihor/fp_newsletter#49]
Hi.

I open this issue to discuss the handling of emails in this extension.

I'm currently using it, because direct_mail_subscription isn't available for TYPO3 and I don't want to (re)develop a whole newsletter registration myself if one is already available.
As I'm french, I need the extension to be fully translated in french (thx captain obvious !)

Thus said there's a few point I would like to discuss.
![image](https://user-images.githubusercontent.com/1927963/160852790-0dc11ac5-0cd5-49d5-a61b-cd47b44989ef.png)

1) The email templates contains locallanged labels and static german text.
-> As the locallang labels seems to work, is it ok to use locallang for every email texts ?
--> If yes, would you mind impacting the locallangs for the default language, thus you can use the locallang key with your own namespaces habits, I would be glad to offer french (and english translations if needed)

2) Emails contains forms (WTF ?) thoses are not working in my outlook, and I'm quite not sure of the security of the point. BTW in almost 20 years using the web I do not remember having seen an email containing a form. Thus theoretically, it should be ok as it is HTML.
![image](https://user-images.githubusercontent.com/1927963/160854013-f04eb2f6-8d60-47fb-a57d-dbd2781a643f.png)
-> Is it possible to get rid of the forms alternatives in the emails ? I guess having a clickable link and a plain text link to copy/paste should be enough.
-> Removing the forms will also get rid of some labels and then reduce the numbers of locallang to setup.
--> For this point I can provide a pull request removing all the forms in the emails templates.

How do you feel about that ?

**Comment by bihor** [comment]
OK, you are right. The form in the email-template was a bad idea.
I will change it to a regular link.

As f:translate works since a while in email-templates too, I can and will replace all the text with locallang.

**Comment by lucmuller** [comment]
> I will change it to a regular link.
-> Link is already here, it'll be fine to simply remove the alternative options and the label introducing it.
> As f:translate works since a while in email-templates too, I can and will replace all the text with locallang.
-> I guess, you can also remove the template for lang id1 with 1 suffixed.

Ping me when you'll be ok with this, I'll provide the french translations in the same way as the previous one.

thanks a lot.
