### ISSUE TITLE
Use Releases / Tags to support composer?

### ISSUE THREAD

**Issue by zolthan** [bihor/fp_newsletter#5]
Hi @bihor ,

are there plans to use git tags and releases to properly support composer?

Best
Sebastian

**Comment by bihor** [comment]
I don´t know what gut tags are. Is there any problem with the composer-file?
Maybe I will try the composer tomorrow the first time.

**Comment by zolthan** [comment]
If you release a tag with the current version of your extension it should be listed in packagist.org and will be available for composer require bihor/fp_newsletter


Von meinem iPhone gesendet

**Comment by bihor** [comment]
Well, I have added it now to Packagist:
https://packagist.org/packages/fixpunkt/
But it does not work:
composer require fixpunkt/fp-newsletter
  [InvalidArgumentException]
  Could not find package fixpunkt/fp-newsletter at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

I don´t know about which tags you are talking. Where do I need to add tags?

**Comment by zolthan** [comment]
In https://help.github.com/en/articles/creating-releases it is described, how a release works.

They will appear here: https://github.com/bihor/fp_newsletter/releases

You should keep the releases in sync with the versions you publish in your extension. So for now you would create a git release with the tag "0.14.1" on the commit https://github.com/bihor/fp_newsletter/commit/422e1abc795a79f09394a9866c8abbffee07547a

If you have any more questions, just ask me :)

**Comment by bihor** [comment]
OK. Thanks for the hint.
I have added a release and now it works for me with the composer.

**Comment by zolthan** [comment]
Perfect. Now it should work. Now if you (or Typo3) updates your extension to 0.14.1 in https://extensions.typo3.org/extension/fp_newsletter/ you should get the feature "Composer support" like direct_mail https://extensions.typo3.org/extension/direct_mail/

I think we can then close the issue.
