### ISSUE TITLE
Error when implementing Google Captcha

### ISSUE THREAD

**Issue by agendartobias** [bihor/fp_newsletter#54]
Hey,

when i enable Google Captcha and i want to subscribe i get this error:

`
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1470230766: Data too long for column 'retoken' at row 1 | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /typo3_source/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 93. Requested URL: https://devsite.dev/?tx_fpnewsletter_pi1%5Baction%5D=create&cHash=9df453270f9a7d1e82a713fe15e0a55c
`
I am using TYPO3 11.5.10 and fp_newsletter 3.0.0

**Comment by bihor** [comment]
Well, I have mad the retoken column bigger in version 3.0.3
That should help, I guess.

**Comment by agendartobias** [comment]
It works. Tnx!
