### ISSUE TITLE
f:uri.action encodes & with &amp; in verify mails

### ISSUE THREAD

**Issue by peerlight** [bihor/fp_newsletter#6]
`&amp; ` in verify links results in "wrong parameters" error at verify page

I had to wrap <f:uri.action> with <f:format.raw> in mail templates

see [https://stackoverflow.com/questions/52060881/typo3-fluid-furi-action-encodes-with-amp](https://stackoverflow.com/questions/52060881/typo3-fluid-furi-action-encodes-with-amp)

**Comment by bihor** [comment]
Oh. Which TYPO3 version have you used? TYPO3 8?

**Comment by bihor** [comment]
Tested with TYPO3 8.7.26 and Firefox.
Links contains &amp; but worked.

**Comment by bihor** [comment]
Contains "& amp ;" (without space).

**Comment by bihor** [comment]
f:format.raw to text-links added.
Is that OK?
