### ISSUE TITLE
non-cachable plugin

### ISSUE THREAD

**Issue by chrcan** [bihor/fp_newsletter#61]
In combination with staticfilecache I get the error message:

`The page has an INTincScript: type: FUNC, userFunc: TYPO3\CMS\Extbase\Core\Bootstrap->run, extensionName: FpNewsletter, pluginName: Pi1`

The newsletter subscription is integrated via a modal window per TS on each page.
Do you have the possibility to make the EXT fp_newslettter cachable?

**Comment by bihor** [comment]
For a non-cacheable option the new action must be static, but it is dynamic.
E.g. there is a random method for a math. captcha.

There is another way for a cacheable way:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/3.2/en-us/Configuration/Index.html#external-fields
You can define an own form and set the target to a page with the fp_newsletter extension.
Is that OK for you?

**Comment by chrcan** [comment]
I have now decided to use the link method and removed the bootstrap modal window where I embed the plugin so it works.

It's a pity that there is no other technical solution.

I have included the bootstrap modal in this way so that you also understand what I mean:

_______________________________________________
TypoScript:
_______________________________________________
```
lib.modalnewsletter_anmeldung = RECORDS
lib.modalnewsletter_anmeldung {
    tables = tt_content
    source = 314
    dontCheckPid = 1
}

[traverse(page, 'uid') == 129]

lib.modalnewsletter_anmeldung >
lib.modalnewsletter_anmeldung = TEXT

[END]
```
_______________________________________________
Templates:
_______________________________________________
```
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <h1>Newsletteranmeldung</h1>

            <f:cObject typoscriptObjectPath="lib.modalnewsletter_anmeldung"/>

        </div>
    </div>
</div>
```

**Comment by bihor** [comment]
I think, your solution is good.
I guess you have a HTML-form in tt_content 314.
But you are right: a new cacheable action would be a great feature.
It should have a form with a target to a create-page.
I think, I will implement it some day.

**Comment by bihor** [comment]
OK, in version 4.0.0 is the new cacheable action "form".
You can test it now.
