### ISSUE TITLE
Move Gender in Translation Files

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_newsletter#63]

**Comment by bihor** [comment]
You can now test it in version 4.0.0 with the setting
preferXlfFile = 1

**Comment by bihor** [comment]
Interne Anmerkung:
es funktioniert nur sowas direkt im Template
<f:translate key="LLL:EXT:fp_newsletter/Resources/Private/Language/locallang.xlf:tx_fpnewsletter_domain_model_log.gender.divers" />
und auch nur für die Standardsprache.

**Comment by bihor** [comment]
I noticed that your solution is wrong:
LocalizationUtility::translate('tx_fpnewsletter_domain_model_log.gender.please', 'fp_newsletter'),
The correct solution is:
LocalizationUtility::translate('tx_fpnewsletter_domain_model_log.gender.please', 'FpNewsletter'),
I have fixed that in version 4.1.1.
Did that really worked in your case?
Can you test the new version?

And I noticed that ._LOCAL_LANG.en does not work anymore. For english this is correct:
._LOCAL_LANG.default
