### ISSUE TITLE
Sender Email and Company Name get overridden for arbitary sys_language_uids

### ISSUE THREAD

**Issue by linawolf** [bihor/fp_newsletter#68]
This is very counter-intuitive

**Comment by bihor** [comment]
I will check it when I have time.

**Comment by bihor** [comment]
Well, I don´t know what you mean. I have tested this on the root page:
```
[siteLanguage("languageId") == "1"]
plugin.tx_fpnewsletter.settings.company = Milk company
[END]
[siteLanguage("languageId") == "2"]
plugin.tx_fpnewsletter.settings.company = Lait company
[END]
```
like described here:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/3.2/en-us/Configuration/Index.html#property-details-examples

It worked for me like expected.
What are your settings and result?

**Comment by linawolf** [comment]
Well I am setting `plugin.tx_fpnewsletter.settings.company = MyCompany` and this gets overridden in sys_language_uid=1 with someothing like "Test Company"

**Comment by linawolf** [comment]
I would therefore suggest to remove lines like https://github.com/bihor/fp_newsletter/blob/619175906d7fc2143cb360021bc4ff4008c7416c/Configuration/TypoScript/setup.ts#L84 and only point to the possibility in the docs

**Comment by bihor** [comment]
OK, thats a good argument.

**Comment by bihor** [comment]
The examples for [siteLanguage("languageId") == "1"] are removed in version 4.0.0
So this problem should be solved.
