### ISSUE TITLE
Fix error handling in deleteAction() function.

### ISSUE THREAD

**Issue by kabi097** [bihor/fp_newsletter#70]
The 'deleteAction' method in LogController.php file is currently not handling the case when the $log parameter is null and the $user['email'] is not set. This can cause an error "Call to a member function getEmail() on null" if user open delete-subscription page manually (by entering URL). 
![error](https://user-images.githubusercontent.com/2821128/210768419-ecf50c8a-3253-4761-ae99-f2bc5f351d7e.png)

**Comment by bihor** [comment]
Fixed in version 4.0.2
