### ISSUE TITLE
TypeError after updating from version 2.2.1 to 4.1.0

### ISSUE THREAD

**Issue by Boa2** [bihor/fp_newsletter#75]
After updating fp_newsletter from 2.2.1 to 4.1.0 I get the following error on the subscription page:

(1/1) TypeError
Argument 1 passed to Fixpunkt\FpNewsletter\Utility\HelpersUtility::getGenders() must be of the type boolean, null given, called in /xxx/typo3conf/ext/fp_newsletter/Classes/Controller/LogController.php on line 122

The site is using Typo3 version 10.4.23 at the moment. I am going to update to Typo3 10.4.36 after the extension updates.

Any idea regarding the TypeError?

**Comment by Boa2** [comment]
Hi Bihor,
unfortunately adding "plugin.tx_fpnewsletter.settings.preferXlfFile = 0" was not successful. But the error message changed to:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to Fixpunkt\FpNewsletter\Utility\HelpersUtility::getGenders() must be of the type array, null given, called in /xxx/typo3conf/ext/fp_newsletter/Classes/Controller/LogController.php on line 122 | TypeError thrown in file /xxx/typo3conf/ext/fp_newsletter/Classes/Utility/HelpersUtility.php in line 153

 I've cleaned the cache via "Flush all caches" and via Maintenance/Flush TYPO3 and PHP Cache.

-Andrea

**Comment by bihor** [comment]
Well, are you including the TypoScript settings of fp_newsletter?
What does your TypoScript Object Browser shows you? Is this missing?
```
plugin.tx_fpnewsletter.settings.gender {
  please = Bitte auswählen
  mr = Herr
  mrs = Frau
  divers = Divers
}
```
Maybe comes the error only for other languages than the default language?
Then you must set the foreign values like this:
```
  [siteLanguage("languageId") == "1"]
  plugin.tx_fpnewsletter.settings.company = Your company
  plugin.tx_fpnewsletter.settings.gender.please = Please select your gender
  plugin.tx_fpnewsletter.settings.gender.mr = Mr.
  plugin.tx_fpnewsletter.settings.gender.mrs = Mrs.
  [END]
```

**Comment by Boa2** [comment]
Thank you so much. I forgot to  include the TypoScript settings of fp_newsletter. 
Now it works like expected.

Thanks,
Andrea
