### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by grosswerner** [bihor/fp_newsletter#78]
Hello,

I use your Extension that works everything, he writes as desired in the tt_adress, I have specified in the registration form that the GPDR (German Datenschutzerklärung) must be ticked. now I would welcome that in this case also the field GDPR of the tt_address is filled. What do I have to do to make this work.

Greetings
Werner Great

**Comment by bihor** [comment]
I can´t see the field gpdr in the tt_address-table:
https://github.com/FriendsOfTYPO3/tt_address/blob/master/ext_tables.sql

You have that field? Maybe its added by another extension?

**Comment by bihor** [comment]
OK, additional fields can now be copied to tt_address. Instruction:

Adding additional fields to tt_address

If you want to add additional fields to tt_address, they must be already present in the log-table (tx_fpnewsletter_domain_model_log) and in the tt_address-table. If they are not present, then you must add the fields to both tables via an own extension in your ext_tables.sql file. Example: you want to add the field "gdpr" to tt_address. This field is already part of the log-table. You need to add it only to the tt_address-table by your own. Then you must specify which additional fields should be copied from the log-table to the tt_address-table via TypoScript:

plugin.tx_fpnewsletter.settings.additionalTtAddressFields = gdpr

That's all.
