### ISSUE TITLE
The action "delete" is not allowed by this plugin / module

### ISSUE THREAD

**Issue by chrcan** [bihor/fp_newsletter#80]
Hello, I am working with the TYPO3 v11.5.28 direct_mail v11.x-dev and the fp-newsletter vv4.1.1

when I send a newsletter with the given link:
https://myddev.ddev.site/sofortabmeldung.html?u=###USER_uid###&t=###SYS_TABLE_NAME###&a=###SYS_AUTHCODE###

this error message appears:

```
(1/1) #1313855175 TYPO3\CMS\Extbase\Mvc\Exception\InvalidActionNameException.
The action "delete" (controller "Fixpunkt\FpNewsletter\Controller\LogController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php.
```

I did everything as described in the documentation:
1. created a new page and immediately logged in the plugin.
`Unsubscribe via direct-mail link Log->unsubscribeDM;Log->unsubscribe;Log->delete;Log->verifyUnsubscribe`

I also tried this one 
`Unsubscribe via form Log->unsubscribeDM;Log->unsubscribe;Log->delete;Log->verifyUnsubscribe`

but I always get the same error message in the FE.

Also in the TS I have set the 
`plugin.tx_fpnewsletter.settings.unsubscribeUid = 139` 
this is the page where the plugin was inserted.

Why does this not work?

And this is all in the URL when I click on the unsubscribe link in the newsletter:
`https://myddev.ddev.site/sofortabmeldung.html?tx_fpnewsletter_pi1%5Baction%5D=delete&tx_fpnewsletter_pi1%5Buser%5D%5Baddress%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bbirthday%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bbuilding%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcategories%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bcity%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcompany%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcountry%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bcrdate%5D=1687527110&tx_fpnewsletter_pi1%5Buser%5D%5Bcruser_id%5D=1&tx_fpnewsletter_pi1%5Buser%5D%5Bdeleted%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bdescription%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bemail%5D=pinkiracan%40gmail.com&tx_fpnewsletter_pi1%5Buser%5D%5Bendtime%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bfacebook%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bfax%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bfe_group%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bfirst_name%5D=Christian&tx_fpnewsletter_pi1%5Buser%5D%5Bgender%5D=m&tx_fpnewsletter_pi1%5Buser%5D%5Bhidden%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bimage%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bl10n_diffsource%5D=%7B%22gender%22%3A%22%22%2C%22title%22%3A%22%22%2C%22title_suffix%22%3A%22%22%2C%22first_name%22%3A%22%22%2C%22middle_name%22%3A%22%22%2C%22last_name%22%3A%22%22%2C%22name%22%3A%22%22%2C%22slug%22%3A%22%22%2C%22image%22%3A%22%22%2C%22description%22%3A%22%22%2C%22address%22%3A%22%22%2C%22city%22%3A%22%22%2C%22zip%22%3A%22%22%2C%22region%22%3A%22%22%2C%22country%22%3A%22%22%2C%22latitude%22%3A%22%22%2C%22longitude%22%3A%22%22%2C%22email%22%3A%22%22%2C%22phone%22%3A%22%22%2C%22mobile%22%3A%22%22%2C%22fax%22%3A%22%22%2C%22www%22%3A%22%22%2C%22birthday%22%3A%22%22%2C%22position%22%3A%22%22%2C%22company%22%3A%22%22%2C%22building%22%3A%22%22%2C%22room%22%3A%22%22%2C%22skype%22%3A%22%22%2C%22twitter%22%3A%22%22%2C%22facebook%22%3A%22%22%2C%22linkedin%22%3A%22%22%2C%22sys_language_uid%22%3A%22%22%2C%22hidden%22%3A%22%22%2C%22starttime%22%3A%22%22%2C%22endtime%22%3A%22%22%2C%22fe_group%22%3A%22%22%2C%22categories%22%3A%22%22%2C%22module_sys_dmail_html%22%3A%22%22%7D&tx_fpnewsletter_pi1%5Buser%5D%5Bl10n_parent%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Blast_name%5D=Racan&tx_fpnewsletter_pi1%5Buser%5D%5Blinkedin%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bmiddle_name%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bmobile%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bmodule_sys_dmail_category%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bmodule_sys_dmail_html%5D=1&tx_fpnewsletter_pi1%5Buser%5D%5Bname%5D=Christian%20Racan&tx_fpnewsletter_pi1%5Buser%5D%5Bphone%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bpid%5D=123&tx_fpnewsletter_pi1%5Buser%5D%5Bposition%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bregion%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Broom%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bskype%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bslug%5D=christian-racan-1&tx_fpnewsletter_pi1%5Buser%5D%5Bsorting%5D=128&tx_fpnewsletter_pi1%5Buser%5D%5Bstarttime%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bsys_language_uid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_oid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_stage%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_state%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3ver_wsid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Bt3_origuid%5D=0&tx_fpnewsletter_pi1%5Buser%5D%5Btitle%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Btitle_suffix%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Btstamp%5D=1687612413&tx_fpnewsletter_pi1%5Buser%5D%5Btwitter%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Buid%5D=1382&tx_fpnewsletter_pi1%5Buser%5D%5Bwww%5D=&tx_fpnewsletter_pi1%5Buser%5D%5Bzip%5D=&cHash=9f0f2b8c790f353c80afc954856c937b`

**Comment by chrcan** [comment]
the problem has been fixed on the live system, unfortunately it doesn't work on the ddev system, but I can't say what the problem is.

**Comment by bihor** [comment]
I guess, you have the fp_newsletter plugin 2 times on that page.
Maybe one is included via TypoScript in the footer?

**Comment by chrcan** [comment]
No, I have only included the fp_newsletter plugin once on the page, but I add it with my own extension via ModalBox, which is not the problem. Something is wrong with my ddev, because after deploying it to the live system, I don't have this problem.

So it is not because of the fp_newsletter extension and can be closed.
I think it's the direct_mail extension in combination with the jupurls....
 
Thank you!
