### ISSUE TITLE
Verifylink leads to Exeption

### ISSUE THREAD

**Issue by fischhase** [bihor/fp_newsletter#82]
Hallo,
thanks for your work. I had es problem with verfying the emal adresse. After clicking ob the link in the verifying mail, TYPO3 shows an exeption:
TargetPageUid has to be int, but string is given
in LogController.php Line 1112

The TargetPageUid was filled with $this->settings['subscribeVerifyMessageUid']. Ich echoed the value and it was the same, I entered in TYPOScript plugin-settings (58). It seams, the settings are string even if it contains a number. 

So I changed this line from:
```
$uri = $this->uriBuilder->reset()
   ->setTargetPageUid($this->settings['subscribeVerifyMessageUid'])
   ->build();
```
to 
```
$uri = $this->uriBuilder->reset()
   ->setTargetPageUid((int)$this->settings['subscribeVerifyMessageUid'])
   ->build();
```

Now it works. I can't push it to git, sorry.

**Comment by bihor** [comment]
Yes, you can´t push to my git repository. A pull request would be the solution,
but now I have made that change and comitted it to version 5.1.2.
