### ISSUE TITLE
Make it possible to use custom tt_address fields

### ISSUE THREAD

**Issue by web-commerce-og** [bihor/fp_newsletter#84]
I have the following use case: 

I needed to extend tt_address with two custom fields and would like to use these in the newsletter subscription. It's easy to add them to the template, but to actually set them when the tt_address item is created. I extended the Log Model too, but as the fields are all set manually in the LogRepository, they aren't set in the created tt_address entry. 
So you would need to  XClass the LogRepository and LogController or use a core signal to modify the database query before it's executed. 
Or is there a easier way I didnt think of?

It would be really nice to be able to use custom tt_address fields in the newsletter subsription in an easier way.

**Comment by bihor** [comment]
Well, I think you can modify the current version to your needs.
I guess, there will no direct_mail version for TYPO3 12.
In that case I would remove the support for direct_mail and tt_address...

**Comment by bihor** [comment]
Well, I have seen the extension "mail" supports tt_address too.
First I will inspect that extension.

**Comment by bihor** [comment]
In version 6 I have added the support for the extension mail + tt_address.
And I tought about the custom fields.
Well, this extension uses fields from tx_fpnewsletter_domain_model_log for tt_address.
That means, that there must be custom fields in the table tx_fpnewsletter_domain_model_log too.
You say, you have added them.
Then there is only the LogRepository remaining.
Maybe the solution is simple:
foreach ($customFields as $customField) {
  $insert[$customField] = $logAddressArray[$customField];
}
The custom fields should be set via settings and the $address-Object must be converted to an array.

**Comment by jacques2017** [comment]
Thank you for the new version 6. Can you make it possible to unsbubsribe with a link from extension mail? Mail uses the fields mail_html and mail_active in table fe_users and table tt_address.  Under TYPO3 11 I uses dm_unsubscribe to unscubscibe.  The unsubscribe link looks like this: 
[my-website]/abmeldung-newsletter?a=###MAIL_AUTHCODE###&t=t&u=###USER_uid###
The authcode-generation from direkt_mail is working whith the authcode from mail
If you set the two fields from mail to 0 its not necessary to set the deleted flag in fe_users (if the fe_user only want to unsubcribe from the newsletter)

**Comment by bihor** [comment]
That are 4 TODOs/wishes till now:
- support custum fields in tt_address (still relevant?)
- support fe_users + mail (till now fe_users works only with luxletter)
- support deleteMode no. 3 (only remove category or mail-flag)
- support authcode of the mail-extension

**Comment by bihor** [comment]
Well, I have done till now:
support fe_users + mail
support deleteMode no. 3 (only remove category or mail-flag)
support authcode of the mail-extension for direct unsubscription.

Maybe you want to test that now.

**Comment by bihor** [comment]
OK, you can now add additional fields to tt_address.


Adding additional fields to tt_address

If you want to add additional fields to tt_address, they must be already present in the log-table (tx_fpnewsletter_domain_model_log) and in the tt_address-table. If they are not present, then you must add the fields to both tables via an own extension in your ext_tables.sql file. Example: you want to add the field "gdpr" to tt_address. This field is already part of the log-table. You need to add it only to the tt_address-table by your own. Then you must specify which additional fields should be copied from the log-table to the tt_address-table via TypoScript:

plugin.tx_fpnewsletter.settings.additionalTtAddressFields = gdpr

That's all.
