### ISSUE TITLE
unsubscribe link in mail template

### ISSUE THREAD

**Issue by Hobokens** [bihor/fp_newsletter#85]
Thanks for your great extension!

In the footer of the mail template I try to add an unsubsribe link (`https://www.domain.com/newsletter/unsubscribe.html?email=###USER_email###`.)

I tried this without success:
`<f:link.page pageUid="62" additionalParams="{email:###USER_email###}" absolute="1">unsubsribe</f:link.page>
`
The error message is:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1256475113: The argument "additionalParams" was registered with type "array", but is of type "string" in view helper "TYPO3\CMS\Fluid\ViewHelpers\Link\PageViewHelper". | InvalidArgumentException thrown in file /hp/bd/ae/bk/www/dev/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 348. Requested URL: https://my-domain.com/newsletter-1/test `

TYPO3 12.4.7, fp_newsletter 6

**Comment by bihor** [comment]
I guess you need to write:
<f:link.page pageUid="62" additionalParams="{email:'###USER_email###'}" absolute="1">unsubsribe</f:link.page> 
'###USER_email###' instead of ###USER_email###.

**Comment by Hobokens** [comment]
Thanks for your advice. 
Following it there is no more error message. I get a link to the page where the user can finish his subscription.

`https://my-domain.de/newsletter/kuendigung?email=%23%23%23USER_email%23%23%23&cHash=9e6cc6ae3c6d549f99a4bdb8f406c249`

I expected that the input field is filled with the user mail address. But the field is empty. Do I misunderstand something?

**Comment by bihor** [comment]
Well, I don´t know why you wrote:
https://my-domain.de/newsletter/unsubscribe?email=%23%23%23USER_email%23%23%23&cHash=9e6cc6ae3c6d549f99a4bdb8f406c249
instaed of
https://my-domain.de/newsletter/unsubscribe?email=###USER_email###&cHash=9e6cc6ae3c6d549f99a4bdb8f406c249
Does f:link.page manipulate the parameter? Then you must use a static link.
And please note that this works only with fp_newsletter 6.0 (and higher).

**Comment by Hobokens** [comment]
I followed your advice on how to write the URL in the template, and the mail also contains the URL in the correct form, i.e. with '#'. 
However, the browsers convert '#' to '%23'.

I am using fp_newsletter v6.0 and TYPO3 12.4.7.

**Comment by bihor** [comment]
You mean, in the newsletter mail is this link:
https://my-domain.de/newsletter/unsubscribe?email=###USER_email###&cHash=9e6cc6ae3c6d549f99a4bdb8f406c249
That should not be the case.
Die Mail-Extension should replace ###USER_email### with the email. Note: that not works for Test-Newsletters.
Well, this is not related to fp_newsletter. The mail-extension is responsible for this.

**Comment by Hobokens** [comment]
>Note: that not works for Test-Newsletters. 

Thanks for this hint. I always tested with the Test-Newsletter :-(
Now I get the email address into the URL:

`https://my-domain.de/newsletter/kuendigung?email=firstname.lastname@posteo.de&cHash=9e6cc6ae3c6d549f99a4bdb8f406c249`

But the URL throws a `404 Error`:

`The page did not exist or was inaccessible. Reason: Request parameters could not be validated (&cHash comparison failed)`

**Comment by bihor** [comment]
If a link genereted by TYPO3-Fluid f:link.page is not valid, it is a bug of TYPO3.
So you should use the link directly instead of f:link.page:
https://my-domain.de/newsletter/unsubscribe?email=###USER_emai###

**Comment by Hobokens** [comment]
TYPO3 12.4.7

I'm sorry, even if I insert the link directly I get an error message;

`The page did not exist or was inaccessible. Reason: Request parameters could not be validated (&cHash empty)`

You can try it here:

[https://studio-fuer-neue-musik.de/newsletter/kuendigung](https://studio-fuer-neue-musik.de/newsletter/kuendigung)

**Comment by bihor** [comment]
Well, the link works!
But when I subscribe to the newsletter, I don´t get any verification-email.

**Comment by bihor** [comment]
Ah OK, this link does not work:
https://studio-fuer-neue-musik.de/newsletter/kuendigung?email?test@domain.de

**Comment by bihor** [comment]
OK, if you have set
[FE][cacheHash][enforceValidation] = 1
then you must add "email" to this list:
[FE][cacheHash][excludedParameters]

**Comment by Hobokens** [comment]
Thanks for the helpful hint. Now TYPO3 no longer shows an error message. Unfortunately, however, the e-mail address is still not automatically entered in the input field when I click on the following link in the newsletter:

`https://studio-fuer-neue-musik.de/newsletter/kuendigung?email=firstname.lastname@mail.de`

**Comment by bihor** [comment]
Have you set the TS-setting parameters.email?
plugin.tx_fpnewsletter.settings.parameters.email = email

**Comment by Hobokens** [comment]
Oh, I didn't know that I have to set this parameter. Now everthing is fine.
Thanks a lot for your support and the great extension.

**Comment by bihor** [comment]
Well, its described here:
https://docs.typo3.org/p/fixpunkt/fp-newsletter/6.0/en-us/Configuration/Index.html#external-fields

Good that it works now.
