### ISSUE TITLE
mail_active field not enabled after successfully subscription

### ISSUE THREAD

**Issue by HorstBaumann** [bihor/fp_newsletter#86]
typo3 11.5.32
fp_newsletter 4.2.0
mail 2.5.2

the subscription works, but the mail_active (and also the mail_html) field in the new created tt_address-record is unset.
how can I set these two fields to checked per default ?

**Comment by bihor** [comment]
Well, it should work when the new setting html is not -1. settings.html should be 1. This is the code:
if ($mode != -1) {
     $insert['mail_html'] = $mode;
     $insert['mail_salutation'] = $salutation;
     $insert['mail_active'] = 1;
}

**Comment by bihor** [comment]
Oh, this works only with fp_newsletter 6.0.
If you use TYPO3 11.5 you can not use it. Therefore I must made the version compatible with TYPO3 11.5.

**Comment by bihor** [comment]
For now I can suggest that you add this lines:
$insert['mail_html'] = 1;
$insert['mail_active'] = 1;
in the function insertInTtAddress in the file Classes/Domain/Repository/LogRepository.php

**Comment by bihor** [comment]
OK, I made version 6.1.0 compatible with TYPO3 11.5.
Maybe you want to test it.
