### ISSUE TITLE
PHP 8.1 warning in the CLI: "Deprecated: Optional parameter"

### ISSUE THREAD

**Issue by baschny** [bihor/fp_newsletter#87]
With latest version and running on PHP 8.1 I get this on the CLI from time to time:

`Deprecated: Optional parameter $dmCatArr declared before required parameter $extension is implicitly treated as a required parameter in /app/html/typo3conf/ext/fp_newsletter/Classes/Domain/Repository/LogRepository.php on line 419`

**Comment by metapublic-gbr** [comment]
I got the same warning in install-tool -> db-compare after installing the extension.
(php 8.1, typo3 12.4, fp-newsletter 6.3.0)
I had to

**Comment by bihor** [comment]
I didn´t got any warning, but you are right.
I fixed this issue in version 6.3.1.
