### ISSUE TITLE
Invalid site key or not loaded in api.js: {settings.reCAPTCHA_site_key}

### ISSUE THREAD

**Issue by agendartobias** [bihor/fp_newsletter#88]
Hey when i implement Google reCaptcha i get this error in console:

`Invalid site key or not loaded in api.js: {settings.reCAPTCHA_site_key}`

After debug it seems that the problem is in two templates:

- https://github.com/bihor/fp_newsletter/blob/c6ede56e7493f901cfe3d3cf011bf3116f518e61/Resources/Private/Partials/Log/FormFields.html#L215
- https://github.com/bihor/fp_newsletter/blob/c6ede56e7493f901cfe3d3cf011bf3116f518e61/Resources/Private/Partials/Log/FormFieldsOut.html#L37

My solution:
change `var recaptcha3keyS = '{settings.reCAPTCHA_site_key}';` to
`var recaptcha3keyS = '<f:format.raw>{settings.reCAPTCHA_site_key}</f:format.raw>';`

But i don't know if this is OK for security?

fp_newsletter version: 6.3.1

If you need i can make Pull request.

**Comment by bihor** [comment]
This is OK for security. I will change it.

**Comment by bihor** [comment]
Fixed in version 6.3.2
