### ISSUE TITLE
No Admin mail is send

### ISSUE THREAD

**Issue by quadronet** [bihor/fp_newsletter#9]
I have check the ext, but the admin mails are not send. 
		adminMail = i have set the email
		adminName = Admin
		adminSubscribeSubject = Neue Newsletter-Anmeldung
		adminUnsubscribeSubject = Neue Newsletter-Abmeldung

**Comment by bihor** [comment]
Currently the email to the admin is send not after verification, but before.
I guess you mean this is the problem.

**Comment by bihor** [comment]
I have changed to default state.
The email to admin will be send now after the email-verification.
Please test it again.

**Comment by djangones** [comment]
In my installation (V1.0.0) the admin mail ist only sent on unregistration from the list.
On registration it is not sent in any of the cases.

**Comment by bihor** [comment]
I have just testet it an it worked.
email.adminMailBeforeVerification = 0
is set?

**Comment by bihor** [comment]
Refactored and completly tested with version 1.2.5.
Worked for me.
