### ISSUE TITLE
Wrong unsubscribe-Link with mail

### ISSUE THREAD

**Issue by jacques2017** [bihor/fp_newsletter#91]
Hi,
I use the mail-estension and in the newsletter-template I added the unsubscribe-link as described in the manual:
https://www.domain.com/newsletter/unsubscribe.html?email=###USER_email###&authcode=###MAIL_AUTHCODE###
but in the Newsletter, I recive the link is:
https://www.domain.com/newsletter/unsubscribe.html?mail=57&rid=fe_users-50717&aC=69135599&jumpurl=2

I set: 
plugin.tx_fpnewsletter.settings.parameters.email = email
plugin.tx_fpnewsletter.settings.parameters.authcode = authcode
plugin.tx_fpnewsletter.settings.newsletterExtension = mail

When I click on the link I get the message: Fehler - E-Mail nicht vorhanden. Die Abmeldung ist fehlgeschlagen.

Can you help me?

**Comment by jacques2017** [comment]
Hello, 
the link is correct.
Jumpurl makes the link look wrong.
However, the link still cannot be processed.
Error message:
Error - The unsubscribe link could not be processed.

**Comment by bihor** [comment]
Well, maybe the folder with the tt_address-entries is not selected on the target page in the plugin?
Otherwise try the debug-output via TypoScript-setting:
plugin.tx_fpnewsletter.settings.debug = 1
What does it say?

**Comment by jacques2017** [comment]
I activate the debug-output, but there is no output. 
I use fe_users, not tt_address, the folder is set in the plugin.

**Comment by bihor** [comment]
I have just tested it and it works well.
I can´t say what the problem is in your case.
![nl1](https://github.com/bihor/fp_newsletter/assets/8191408/859d6c81-6622-471b-a8ec-2ba30862f71e)
![nl2](https://github.com/bihor/fp_newsletter/assets/8191408/004ec749-24f2-4e95-aaf6-754953a303f0)
![nl3](https://github.com/bihor/fp_newsletter/assets/8191408/5fa527f4-d068-4cf4-ab07-023ed7234090)

**Comment by bihor** [comment]
Not: this does not work with test-emails.

**Comment by bihor** [comment]
Did you set this TypoScript?
plugin.tx_fpnewsletter.settings.authCodeFields = gender,name

**Comment by jacques2017** [comment]
I've found the first problem, In the plugin I set two folders for the fe_users, but only the first is used to select the user:
![grafik](https://github.com/bihor/fp_newsletter/assets/26480486/83e50e46-7092-40e5-bea5-e2c647b0004e)
And I set this option
![grafik](https://github.com/bihor/fp_newsletter/assets/26480486/d3e4abdf-3c49-4b3d-9470-c218e445ff3f)
I think now the hash is still the problem
Which AuthCode fields are the right ones?
I have tried "gende,name", but without success. I get the following message:
![grafik](https://github.com/bihor/fp_newsletter/assets/26480486/5ec89e72-4db2-43d4-a1d6-48dff92437a5)

**Comment by jacques2017** [comment]
I found the correct settings. Now it works. 
Thank you.

**Comment by bihor** [comment]
Yes, you are right, only the first folder is taken here.
I should fix it...

**Comment by bihor** [comment]
The search in all folders should now work with version 7.0.1.
