### ISSUE TITLE
TCA migration

### ISSUE THREAD

**Issue by seirerman** [bihor/fp_newsletter#92]
'Check TCA Migrations' in Install Tool/Upgrade says:

> The TCA field 'sys_language_uid' of table 'tx_fpnewsletter_domain_model_log' is defined as the 'languageField' and should therefore use the TCA type 'language' instead of TCA type 'select' with 'foreign_table=sys_language' or 'special=languages'.

Probably only a small issue, but I thought I'd mention it here.

Tested on TYPO3 11.5.36 with fp_newsletter 4.2.0, but Configuration/TCA/tx_fpnewsletter_domain_model_log.php of fp_newsletter 6.4.3 still uses 
```
                'type' => 'select',
                'special' => 'languages',
```

**Comment by bihor** [comment]
I will take a look at it next week

**Comment by bihor** [comment]
OK, I have changed this in version 7.0.0.
