### ISSUE TITLE
Import of TypoScript files with .ts no longer works

### ISSUE THREAD

**Issue by michael-binder** [bihor/fp_newsletter#93]
We use the import function of TypoScript with
`@import 'EXT:fp_newsletter/configuration/TypoScript/*.ts'`
Since TYPO3 12, this solution no longer works because of the '.ts' extension. 

By changing the file extension to '.typoscript' the import works again. 
This is also the recommended way, see
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97816-TypoScriptSyntaxChanges.html#import-is-more-restrictive-with-wildcards

Tested with
TYPO3 12
PHP 8.1

**Comment by bihor** [comment]
OK, this is now in version 7.0.0.
