### ISSUE TITLE
Error:  Fehler - Der Link konnte nicht verarbeitet werden.

### ISSUE THREAD

**Issue by taunusweb** [bihor/fp_newsletter#95]
Hi, I'd like to use the Plugin
"Abmeldung via Formular", but I get the following Error:
"Fehler - Der Link konnte nicht verarbeitet werden."
The Registration works as expected,

TYPO3 11LTS and fp_newsletter 6.4.2

Thanks 

Uli

**Comment by taunusweb** [comment]
That would be o.k. for me, but I don't know, how to do?
I have a Page with the Plugin "Abmeldung via Formular" in the Flexform I set a page for "Seite für die Verifikation bei der Abmeldung", there is the Plugin "Abmeldung verifizieren" located, but that seems not to be correct.

**Comment by bihor** [comment]
![abmeldung](https://github.com/bihor/fp_newsletter/assets/8191408/280fde79-4725-4ec3-8241-ce39b63f6351)
The solution is easy: select at the current page the same page at "Seite für die Abmeldung".
For me that works.

**Comment by taunusweb** [comment]
Thanks, that works!
