### ISSUE TITLE
Problem with upgrade wizard in install tool

### ISSUE THREAD

**Issue by p380** [bihor/fp_newsletter#98]
after upgrading the module in the install tool, on the upgrade wizard 'Migrates plugin and settings of existing fp_newsletter plugins using switchableControllerActions' , get the error below

PHP Warning: foreach() argument must be of type array|object, string given in
fp_newsletter/Classes/Updates/SwitchableControllerActionsPluginUpdater.php line 154

**Comment by bihor** [comment]
I have never seen this warning.
Nevertheless I hope that it is fixed now in version 7.0.3.

**Comment by p380** [comment]
thanx
works OK
